name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  packages: write

jobs:
  build-test-scan-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps for CI
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run black (format check)
        run: |
          pip install black==24.4.2
          black --check .

      - name: Run flake8 (lint)
        run: |
          pip install flake8==7.1.1
          flake8 --ignore=E501 .

      - name: Run tests
        run: |
          pip install pytest==8.2.2
          PYTHONPATH=. pytest -q

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ secrets.GHCR_USER }}/hello-devops:latest
            ghcr.io/${{ secrets.GHCR_USER }}/hello-devops:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Scan pushed image with Trivy
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ghcr.io/${{ secrets.GHCR_USER }}/hello-devops:latest
          format: 'table'
          exit-code: '1'
          vuln-type: 'os,library'
