name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-test-scan-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run linting
        run: flake8 --ignore=E501 .

      - name: Run tests
        run: PYTHONPATH=. pytest -v

      - name: Build Docker image
        run: docker build -t hello-devops .

      - name: Scan Docker image (fail on HIGH/CRITICAL vulns)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: hello-devops
          format: table
          exit-code: 1
          ignore-unfixed: true
          severity: HIGH,CRITICAL

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ secrets.GHCR_USER }}/hello-devops:latest
            ghcr.io/${{ secrets.GHCR_USER }}/hello-devops:${{ github.sha }}
