name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Log in to GHCR
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_PAT }}

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Run linting
      - name: Run linting
        run: flake8 --ignore=E501 .

      # Run tests
      - name: Run tests
        run: pytest -v

      # Build Docker image (locally)
      - name: Build Docker image
        run: docker build -t hello-devops:latest .

      # Security scan BEFORE push
      - name: Scan local image with Trivy
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: hello-devops:latest
          format: 'table'
          exit-code: '1'   # Fail if vulnerabilities found
          vuln-type: 'os,library'
          severity: 'CRITICAL'

      # Push Docker image only if scan passes
      - name: Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ secrets.GHCR_USER }}/hello-devops:latest
            ghcr.io/${{ secrets.GHCR_USER }}/hello-devops:${{ github.sha }}
